version: 2
registries:
  gem-fury:
    type: rubygems-server
    url: https://gem.fury.io/enderahmetyurt
    token: ${{secrets.BUNDLE_GEM__FURY__IO}}
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    registries:
      - gem-fury
    schedule:
      interval: daily
