version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        BUNDLE_WITHOUT: ${BUNDLE_WITHOUT}
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      REDIS_URL: redis://redis:6379
      RAILS_ENV: ${RAILS_ENV}
      RACK_ENV: ${RAILS_ENV}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    volumes:
      - .:/app
      - bundle:/bundle
      - logs:/log
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6369:6379"

volumes:
  bundle:
  logs:
  postgres-data:
