version: '3'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec rails s -b 0.0.0.0
    volumes:
      - .:/app
      - bundle:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  redis:
    image: redis
    restart: always

volumes:
  bundle:
