local: &local
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379" } %>

development: *local
test: *local

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://redis:6379/1" } %>
  channel_prefix: spotipods_production
