# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

podcasts = [{:uid=>"0NcPFV7I93Id7fpLUhFVKJ", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Self-help", "uri"=>"spotify:genre:0JQ5DAqbMKFLPhtHltUeTr"}]},
{:uid=>"5L84QuZlUsILySyMZNM07W", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Finance", "uri"=>"spotify:genre:0JQ5IMCbQBLrxSDV6Xi6kN"}, {"__typename"=>"PodcastTopic", "title"=>"Business", "uri"=>"spotify:genre:0JQ5DAqbMKFK0EBNV8Wn6R"}, {"__typename"=>"PodcastTopic", "title"=>"Technology", "uri"=>"spotify:genre:tech_interviews_podcasts"}]},
{:uid=>"6ubzqFvDN5wUmsUH5DRJVw", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Comedy", "uri"=>"spotify:genre:0JQ5DAqbMKFNr6gDrHHVKL"}]},
{:uid=>"32p08HngccrVVyugc45Ljp", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Comedy", "uri"=>"spotify:genre:0JQ5DAqbMKFNr6gDrHHVKL"}]},
{:uid=>"1ug9njZpEHg6aOyzUHPkFE", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Business", "uri"=>"spotify:genre:0JQ5DAqbMKFK0EBNV8Wn6R"}]},
{:uid=>"2ChcmSCLZ4njfh1DKwPV7y", :genres=>[]},
{:uid=>"25cFfnG3lGuypTerKDxKia", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Society", "uri"=>"spotify:genre:0JQ5DAqbMKFLFBJyefzcxG"}, {"__typename"=>"PodcastTopic", "title"=>"Culture", "uri"=>"spotify:genre:0JQ5DAqbMKFP9ywiCs8qKW"}]},
{:uid=>"4Zkj8TTa7XAZYI6aFetlec", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"History", "uri"=>"spotify:genre:0JQ5DAqbMKFKK9EFSCDuOS"}]},
{:uid=>"5XkQKdM3T36kHZaHOooqj2", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Technology", "uri"=>"spotify:genre:tech_interviews_podcasts"}]},
{:uid=>"5Dtru4Q7EzZaY41IACrQ0u", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Philosophy", "uri"=>"spotify:genre:0JQ5IMCbQBLjLJlIwYDak9"}]},
{:uid=>"2XYFdbSghfwHjmh7lR4zAi", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Careers", "uri"=>"spotify:genre:0JQ5DAqbMKFMnJvsZliRJL"}, {"__typename"=>"PodcastTopic", "title"=>"Business", "uri"=>"spotify:genre:0JQ5DAqbMKFK0EBNV8Wn6R"}, {"__typename"=>"PodcastTopic", "title"=>"Technology", "uri"=>"spotify:genre:tech_interviews_podcasts"}]},
{:uid=>"7H43cPPVvHxRob3qE00RAE", :genres=>[]},
{:uid=>"5gCTSMHzLofJPzCRKbF37V", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Society", "uri"=>"spotify:genre:0JQ5DAqbMKFLFBJyefzcxG"}, {"__typename"=>"PodcastTopic", "title"=>"Culture", "uri"=>"spotify:genre:0JQ5DAqbMKFP9ywiCs8qKW"}, {"__typename"=>"PodcastTopic", "title"=>"Comedy", "uri"=>"spotify:genre:0JQ5DAqbMKFNr6gDrHHVKL"}]},
{:uid=>"372apzy004OiOlegW7tqFz", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Relationships", "uri"=>"spotify:genre:0JQ5DAqbMKFIbOFW5Avg3a"}]},
{:uid=>"7AVu47DIP4G9YGMJXtMgRi", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Society", "uri"=>"spotify:genre:0JQ5DAqbMKFLFBJyefzcxG"}, {"__typename"=>"PodcastTopic", "title"=>"History", "uri"=>"spotify:genre:0JQ5DAqbMKFKK9EFSCDuOS"}, {"__typename"=>"PodcastTopic", "title"=>"Culture", "uri"=>"spotify:genre:0JQ5DAqbMKFP9ywiCs8qKW"}]},
{:uid=>"2BTDPFDY7V3jrtT6JzQ0fX", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Self-help", "uri"=>"spotify:genre:0JQ5DAqbMKFLPhtHltUeTr"}, {"__typename"=>"PodcastTopic", "title"=>"Business", "uri"=>"spotify:genre:0JQ5DAqbMKFK0EBNV8Wn6R"}]},
{:uid=>"0e1KN182aQsnx4qk1nN3Mf", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Relationships", "uri"=>"spotify:genre:0JQ5DAqbMKFIbOFW5Avg3a"}]},
{:uid=>"7AWPA88pmIX7qT1RkAQ7Hk", :genres=>[]},
{:uid=>"4PCMBVAH14SJu42mL0U5KU", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Technology", "uri"=>"spotify:genre:tech_interviews_podcasts"}]},
{:uid=>"3ImqTb6CcfZINTgByeAThh", :genres=>[]},
{:uid=>"6Bzt3R5RQAMTMoOODqzY4q", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Business", "uri"=>"spotify:genre:0JQ5DAqbMKFK0EBNV8Wn6R"}]},
{:uid=>"071MWjkyGLCJTTEQl5Ew3R", :genres=>[]},
{:uid=>"3pCF6hcNsAHKlKAillCOuZ", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Society", "uri"=>"spotify:genre:0JQ5DAqbMKFLFBJyefzcxG"}, {"__typename"=>"PodcastTopic", "title"=>"Science", "uri"=>"spotify:genre:0JQ5IMCbQBLzqj7yQzZb03"}, {"__typename"=>"PodcastTopic", "title"=>"Culture", "uri"=>"spotify:genre:0JQ5DAqbMKFP9ywiCs8qKW"}]},
{:uid=>"3ugW9QfSKmL3AWx8N7thmd", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Health", "uri"=>"spotify:genre:health_podcasts"}]},
{:uid=>"43SK48tsAeDNXkrAUZViO5", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Business", "uri"=>"spotify:genre:0JQ5DAqbMKFK0EBNV8Wn6R"}]},
{:uid=>"4ZJ9PgexJIfXGMnQ0dSc2S", :genres=>[]},
{:uid=>"48EAkXWetlbOhhAZwK1Wom", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Careers", "uri"=>"spotify:genre:0JQ5DAqbMKFMnJvsZliRJL"}]},
{:uid=>"3HP0JpgZyDLyyyY7UGMkpF", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Technology", "uri"=>"spotify:genre:tech_interviews_podcasts"}]},
{:uid=>"0rOatMqaG3wB5BF4AdsrSX", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"History", "uri"=>"spotify:genre:0JQ5DAqbMKFKK9EFSCDuOS"}, {"__typename"=>"PodcastTopic", "title"=>"Stories", "uri"=>"spotify:genre:0JQ5DAqbMKFHv2c1dK1Jdi"}]},
{:uid=>"7mACo97JvUL1LOmVJ9lATI", :genres=>[]},
{:uid=>"6azTkzszkQz9M38nPSRU2f", :genres=>[]},
{:uid=>"6WuDqzOExdEP7ugRgMCsJ7", :genres=>[]},
{:uid=>"2a0mPVkGqmHEM9o0ng7qY3", :genres=>[]},
{:uid=>"5T1519uHGVd6Te2xF5tKkR", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Documentary", "uri"=>"spotify:genre:0JQ5DAqbMKFCWOPjGCVIq4"}, {"__typename"=>"PodcastTopic", "title"=>"Comedy", "uri"=>"spotify:genre:0JQ5DAqbMKFNr6gDrHHVKL"}]},
{:uid=>"1JXx4pYPxVO0fHtURYbeK1", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Business", "uri"=>"spotify:genre:0JQ5DAqbMKFK0EBNV8Wn6R"}]},
{:uid=>"1hIFaLAL310EBjvpiSl7Zh", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Marketing", "uri"=>"spotify:genre:0JQ5IMCbQBLjlqsYQ6tkLI"}, {"__typename"=>"PodcastTopic", "title"=>"Technology", "uri"=>"spotify:genre:tech_interviews_podcasts"}]},
{:uid=>"0fhW2Xj66JcumYeh6gljZY", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Marketing", "uri"=>"spotify:genre:0JQ5IMCbQBLjlqsYQ6tkLI"}, {"__typename"=>"PodcastTopic", "title"=>"Self-help", "uri"=>"spotify:genre:0JQ5DAqbMKFLPhtHltUeTr"}]},
{:uid=>"5HiPLSyoTmlzs2eHMoUVNb", :genres=>[]},
{:uid=>"6E1ItjUVm9pZdsJrdLuXuS", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Business", "uri"=>"spotify:genre:0JQ5DAqbMKFK0EBNV8Wn6R"}, {"__typename"=>"PodcastTopic", "title"=>"Technology", "uri"=>"spotify:genre:tech_interviews_podcasts"}]},
{:uid=>"29QF7afl5LUNzjdSecOdnj", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Design & Architecture", "uri"=>"spotify:genre:0JQ5DAqbMKFDx4Q5Zh2Fzg"}]},
{:uid=>"27MkwPxDfBj6qTTENpUuOS", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"How-to", "uri"=>"spotify:genre:how_to_podcasts"}, {"__typename"=>"PodcastTopic", "title"=>"Business", "uri"=>"spotify:genre:0JQ5DAqbMKFK0EBNV8Wn6R"}]},
{:uid=>"5o0S5z1vKu6TpvMFGwzJrR", :genres=>[]},
{:uid=>"4TThBJMknUMe961UTxCF0x", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Careers", "uri"=>"spotify:genre:0JQ5DAqbMKFMnJvsZliRJL"}]},
{:uid=>"5X5tpUcD3r4kqSXUeAHDoT", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Business", "uri"=>"spotify:genre:0JQ5DAqbMKFK0EBNV8Wn6R"}, {"__typename"=>"PodcastTopic", "title"=>"Technology", "uri"=>"spotify:genre:tech_interviews_podcasts"}, {"__typename"=>"PodcastTopic", "title"=>"Design & Architecture", "uri"=>"spotify:genre:0JQ5DAqbMKFDx4Q5Zh2Fzg"}]},
{:uid=>"1tOJ4gwuVcGHnA3humqR8c", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Careers", "uri"=>"spotify:genre:0JQ5DAqbMKFMnJvsZliRJL"}, {"__typename"=>"PodcastTopic", "title"=>"Business", "uri"=>"spotify:genre:0JQ5DAqbMKFK0EBNV8Wn6R"}]},
{:uid=>"4fK3jhDYaP0JngsDGCHRxn", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Business", "uri"=>"spotify:genre:0JQ5DAqbMKFK0EBNV8Wn6R"}, {"__typename"=>"PodcastTopic", "title"=>"Technology", "uri"=>"spotify:genre:tech_interviews_podcasts"}]},
{:uid=>"3MwPqZj5xZondA1qgeuMSO", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Careers", "uri"=>"spotify:genre:0JQ5DAqbMKFMnJvsZliRJL"}, {"__typename"=>"PodcastTopic", "title"=>"Marketing", "uri"=>"spotify:genre:0JQ5IMCbQBLjlqsYQ6tkLI"}, {"__typename"=>"PodcastTopic", "title"=>"Business", "uri"=>"spotify:genre:0JQ5DAqbMKFK0EBNV8Wn6R"}]},
{:uid=>"2fBNTcCbfTWCN7uRvOU85e", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Business", "uri"=>"spotify:genre:0JQ5DAqbMKFK0EBNV8Wn6R"}, {"__typename"=>"PodcastTopic", "title"=>"Technology", "uri"=>"spotify:genre:tech_interviews_podcasts"}]},
{:uid=>"2iYIkHGp1wX205VHCH7zNo", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Books", "uri"=>"spotify:genre:0JQ5DAqbMKFD0Jc9BXRvme"}]},
{:uid=>"2oHcQ3QX0lYnPMGGqRKbma", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Self-help", "uri"=>"spotify:genre:0JQ5DAqbMKFLPhtHltUeTr"}]},
{:uid=>"4OsuS4G6ukepPsjme51uFt", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Business", "uri"=>"spotify:genre:0JQ5DAqbMKFK0EBNV8Wn6R"}, {"__typename"=>"PodcastTopic", "title"=>"Technology", "uri"=>"spotify:genre:tech_interviews_podcasts"}]},
{:uid=>"4dKzwk2dDQTI83QZf62SMH", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"TV", "uri"=>"spotify:genre:0JQ5IMCbQBLo64OouK01L3"}, {"__typename"=>"PodcastTopic", "title"=>"Entertainment", "uri"=>"spotify:genre:entertainment_v2_podcasts"}]},
{:uid=>"2oUKoR1lRiUGRgoAjC1FkF", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"How-to", "uri"=>"spotify:genre:how_to_podcasts"}, {"__typename"=>"PodcastTopic", "title"=>"Marketing", "uri"=>"spotify:genre:0JQ5IMCbQBLjlqsYQ6tkLI"}]},
{:uid=>"4FO3zzr000gz6bmo4bdAcd", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Football", "uri"=>"spotify:genre:0JQ5DAqbMKFLPwE3vGBDOP"}]},
{:uid=>"29sSPT3klTiBHgGkQh8Gcp", :genres=>[]},
{:uid=>"2qJVeu47e2eAum4j7lxXXv", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Technology", "uri"=>"spotify:genre:tech_interviews_podcasts"}]},
{:uid=>"15Xf04XGXROOKujzHeAquq", :genres=>[]},
{:uid=>"3EM9APeoSjJe4yfIaVfCVO", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Technology", "uri"=>"spotify:genre:tech_interviews_podcasts"}, {"__typename"=>"PodcastTopic", "title"=>"Comedy", "uri"=>"spotify:genre:0JQ5DAqbMKFNr6gDrHHVKL"}]},
{:uid=>"6YUI2bCL5CWGM851qNZRk3", :genres=>[]},
{:uid=>"1chSKGvRimrPCqvcdOtyU3", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Careers", "uri"=>"spotify:genre:0JQ5DAqbMKFMnJvsZliRJL"}, {"__typename"=>"PodcastTopic", "title"=>"Marketing", "uri"=>"spotify:genre:0JQ5IMCbQBLjlqsYQ6tkLI"}]},
{:uid=>"2Cv0V85tssliSL8wz7gVWm", :genres=>[]},
{:uid=>"5dEsgMhmVy7wK8TSUrVnsQ", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Film", "uri"=>"spotify:genre:0JQ5IMCbQBLBylyI0RX5u8"}, {"__typename"=>"PodcastTopic", "title"=>"Personal stories", "uri"=>"spotify:genre:0JQ5DAqbMKFIHya0xgnxbE"}, {"__typename"=>"PodcastTopic", "title"=>"Comedy", "uri"=>"spotify:genre:0JQ5DAqbMKFNr6gDrHHVKL"}]},
{:uid=>"3V4beOnTIEUVtPqP8me1Mq", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Society", "uri"=>"spotify:genre:0JQ5DAqbMKFLFBJyefzcxG"}, {"__typename"=>"PodcastTopic", "title"=>"Culture", "uri"=>"spotify:genre:0JQ5DAqbMKFP9ywiCs8qKW"}]},
{:uid=>"4a3o2Y79Qxts15QYvBtnkq", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"How-to", "uri"=>"spotify:genre:how_to_podcasts"}, {"__typename"=>"PodcastTopic", "title"=>"Business", "uri"=>"spotify:genre:0JQ5DAqbMKFK0EBNV8Wn6R"}, {"__typename"=>"PodcastTopic", "title"=>"Educational podcasts", "uri"=>"spotify:genre:educational_podcasts"}]},
{:uid=>"4p777LvCVOVPxixcpqRP9v", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Entertainment", "uri"=>"spotify:genre:entertainment_v2_podcasts"}]},
{:uid=>"6olvQhNhQwMbGG26t3rVgM", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Comedy", "uri"=>"spotify:genre:0JQ5DAqbMKFNr6gDrHHVKL"}]},
{:uid=>"4UQQligFVKcY436jqQEsIn", :genres=>[]},
{:uid=>"7GWjLNTWLUvUmrxidV5WKH", :genres=>[]},
{:uid=>"79dG1ZEIiMY23ipSC5VTco", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Careers", "uri"=>"spotify:genre:0JQ5DAqbMKFMnJvsZliRJL"}]},
{:uid=>"3mliji9352UAk3XnWElnDV", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Marketing", "uri"=>"spotify:genre:0JQ5IMCbQBLjlqsYQ6tkLI"}]},
{:uid=>"6e4HNBdPvjDOHKVf82oMEk", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Self-help", "uri"=>"spotify:genre:0JQ5DAqbMKFLPhtHltUeTr"}, {"__typename"=>"PodcastTopic", "title"=>"Philosophy", "uri"=>"spotify:genre:0JQ5IMCbQBLjLJlIwYDak9"}]},
{:uid=>"3yH2dT11kJvJoSZkmeVEsM", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Business", "uri"=>"spotify:genre:0JQ5DAqbMKFK0EBNV8Wn6R"}]},
{:uid=>"5UXYSSVqJ8vfNl8DdpIE21", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Business", "uri"=>"spotify:genre:0JQ5DAqbMKFK0EBNV8Wn6R"}]},
{:uid=>"7jXukSsc4hJpRE9VGgtzjO", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Health", "uri"=>"spotify:genre:health_podcasts"}, {"__typename"=>"PodcastTopic", "title"=>"Business", "uri"=>"spotify:genre:0JQ5DAqbMKFK0EBNV8Wn6R"}]},
{:uid=>"7ob6aHmjYmbv0WhIFnhCLB", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Society", "uri"=>"spotify:genre:0JQ5DAqbMKFLFBJyefzcxG"}, {"__typename"=>"PodcastTopic", "title"=>"Culture", "uri"=>"spotify:genre:0JQ5DAqbMKFP9ywiCs8qKW"}]},
{:uid=>"5rJQ7bpPcjU2HHpjEwXNAi", :genres=>[]},
{:uid=>"67EPVbpyjlDxGWsrfzdYu5", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Society", "uri"=>"spotify:genre:0JQ5DAqbMKFLFBJyefzcxG"}, {"__typename"=>"PodcastTopic", "title"=>"History", "uri"=>"spotify:genre:0JQ5DAqbMKFKK9EFSCDuOS"}, {"__typename"=>"PodcastTopic", "title"=>"Culture", "uri"=>"spotify:genre:0JQ5DAqbMKFP9ywiCs8qKW"}]},
{:uid=>"5O49ibTfrV1GrN1XVBg4vE", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Business", "uri"=>"spotify:genre:0JQ5DAqbMKFK0EBNV8Wn6R"}, {"__typename"=>"PodcastTopic", "title"=>"Technology", "uri"=>"spotify:genre:tech_interviews_podcasts"}]},
{:uid=>"6AJEwMEWe1lBN2Tle2NTQJ", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Technology", "uri"=>"spotify:genre:tech_interviews_podcasts"}]},
{:uid=>"1DjQ9TBzvB3B4xUgGWSVsB", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Comedy", "uri"=>"spotify:genre:0JQ5DAqbMKFNr6gDrHHVKL"}]},
{:uid=>"4KPqMHIB3wT5fvWxDIz7YV", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Technology", "uri"=>"spotify:genre:tech_interviews_podcasts"}]},
{:uid=>"2vMZ1GTqZOrEjFsuEOFN4P", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Business", "uri"=>"spotify:genre:0JQ5DAqbMKFK0EBNV8Wn6R"}, {"__typename"=>"PodcastTopic", "title"=>"Technology", "uri"=>"spotify:genre:tech_interviews_podcasts"}]},
{:uid=>"76h8fh9KK3boiMrQ340lV4", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Technology", "uri"=>"spotify:genre:tech_interviews_podcasts"}]},
{:uid=>"2JSZvqENj2i9ZN3ovEOivJ", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Technology", "uri"=>"spotify:genre:tech_interviews_podcasts"}]},
{:uid=>"72o7yWXWuGR3A1bsTjUXYd", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Language", "uri"=>"spotify:genre:0JQ5DAqbMKFGvEvBJcLHVZ"}, {"__typename"=>"PodcastTopic", "title"=>"Educational podcasts", "uri"=>"spotify:genre:educational_podcasts"}]},
{:uid=>"1IUpXIJ1czUcbqKYjVsux5", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Philosophy", "uri"=>"spotify:genre:0JQ5IMCbQBLjLJlIwYDak9"}, {"__typename"=>"PodcastTopic", "title"=>"Books", "uri"=>"spotify:genre:0JQ5DAqbMKFD0Jc9BXRvme"}]},
{:uid=>"5vRszSJp0ziAzkXsKVn7s2", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Society", "uri"=>"spotify:genre:0JQ5DAqbMKFLFBJyefzcxG"}, {"__typename"=>"PodcastTopic", "title"=>"Culture", "uri"=>"spotify:genre:0JQ5DAqbMKFP9ywiCs8qKW"}]},
{:uid=>"41YAmZVgt14kjP0TE2vr9b", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Business", "uri"=>"spotify:genre:0JQ5DAqbMKFK0EBNV8Wn6R"}, {"__typename"=>"PodcastTopic", "title"=>"Technology", "uri"=>"spotify:genre:tech_interviews_podcasts"}]},
{:uid=>"7wdHlpy9tcPhv2g6IpI97C", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Economics", "uri"=>"spotify:genre:0JQ5IMCbQBLkCuGhI0Epb1"}, {"__typename"=>"PodcastTopic", "title"=>"Finance", "uri"=>"spotify:genre:0JQ5IMCbQBLrxSDV6Xi6kN"}]},
{:uid=>"5HoEeN5pLHQS9f0B3TRpvE", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Technology", "uri"=>"spotify:genre:tech_interviews_podcasts"}]},
{:uid=>"4BuXlpcana6xU2ctfZ3qgZ", :genres=>[]},
{:uid=>"0TbZLEvRcQNoFzWQFHddJ1", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"True crime", "uri"=>"spotify:genre:true_crime_podcasts"}, {"__typename"=>"PodcastTopic", "title"=>"Documentary", "uri"=>"spotify:genre:0JQ5DAqbMKFCWOPjGCVIq4"}]},
{:uid=>"1GdTMF4b8x5WTJuk66enCq", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Society", "uri"=>"spotify:genre:0JQ5DAqbMKFLFBJyefzcxG"}, {"__typename"=>"PodcastTopic", "title"=>"Culture", "uri"=>"spotify:genre:0JQ5DAqbMKFP9ywiCs8qKW"}]},
{:uid=>"2NLG4Opu8aqdo3sOxrI7oe", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Society", "uri"=>"spotify:genre:0JQ5DAqbMKFLFBJyefzcxG"}, {"__typename"=>"PodcastTopic", "title"=>"Culture", "uri"=>"spotify:genre:0JQ5DAqbMKFP9ywiCs8qKW"}]},
{:uid=>"5kwtpnUDQEff95r55gFSp2", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"History", "uri"=>"spotify:genre:0JQ5DAqbMKFKK9EFSCDuOS"}]},
{:uid=>"5H75iItCx63UK6QKh4xZnE", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"History", "uri"=>"spotify:genre:0JQ5DAqbMKFKK9EFSCDuOS"}]},
{:uid=>"3WfWCCaiYRltqk3W87Psc1", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"History", "uri"=>"spotify:genre:0JQ5DAqbMKFKK9EFSCDuOS"}]},
{:uid=>"4jOl0vgjFuV9bm7NUIvUAW", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Technology", "uri"=>"spotify:genre:tech_interviews_podcasts"}]},
{:uid=>"4TGY8xeVhvb2q9EcUae4AD", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Stories", "uri"=>"spotify:genre:0JQ5DAqbMKFHv2c1dK1Jdi"}]},
{:uid=>"0cdSqKe9gkm2KXpMFxPr1m", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Personal stories", "uri"=>"spotify:genre:0JQ5DAqbMKFIHya0xgnxbE"}]},
{:uid=>"3Xz1vlDE32UCCzZnpIX7J4", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Society", "uri"=>"spotify:genre:0JQ5DAqbMKFLFBJyefzcxG"}, {"__typename"=>"PodcastTopic", "title"=>"Culture", "uri"=>"spotify:genre:0JQ5DAqbMKFP9ywiCs8qKW"}]},
{:uid=>"3DwfH1K0Sj8zqUSmFiuRy1", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Society", "uri"=>"spotify:genre:0JQ5DAqbMKFLFBJyefzcxG"}, {"__typename"=>"PodcastTopic", "title"=>"Culture", "uri"=>"spotify:genre:0JQ5DAqbMKFP9ywiCs8qKW"}]},
{:uid=>"2XRaRBypiEIf2FfnltL3eK", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Documentary", "uri"=>"spotify:genre:0JQ5DAqbMKFCWOPjGCVIq4"}, {"__typename"=>"PodcastTopic", "title"=>"Culture", "uri"=>"spotify:genre:0JQ5DAqbMKFP9ywiCs8qKW"}, {"__typename"=>"PodcastTopic", "title"=>"Entertainment", "uri"=>"spotify:genre:entertainment_v2_podcasts"}]},
{:uid=>"166TvAvdRhDBLLdRwOikii", :genres=>[]},
{:uid=>"6YIm23KPwxoWDpcnlwGwLP", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Design & Architecture", "uri"=>"spotify:genre:0JQ5DAqbMKFDx4Q5Zh2Fzg"}]},
{:uid=>"6T9XHu1OBsB5m9xi7oVKe1", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Celebrities", "uri"=>"spotify:genre:0JQ5IMCbQBLwyf3yahCa0M"}, {"__typename"=>"PodcastTopic", "title"=>"Pop culture", "uri"=>"spotify:genre:0JQ5IMCbQBLm1xnyRGiyzw"}]},
{:uid=>"41QZuEijl9N7OloHvDXm6S", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Technology", "uri"=>"spotify:genre:tech_interviews_podcasts"}]},
{:uid=>"3RScKBgW5IKUpmStyLLp5j", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Philosophy", "uri"=>"spotify:genre:0JQ5IMCbQBLjLJlIwYDak9"}]},
{:uid=>"1WErgoXiZwgctkHLzqU6nf", :genres=>[]},
{:uid=>"7oKXOpbHzbICFUcJNbZ5wF", :genres=>[]},
{:uid=>"1Bmx7t2vYAa1jGUeJ9f2BO", :genres=>[]},
{:uid=>"20ch3IIqtWSSM4nfy11ZzP", :genres=>[]},
{:uid=>"7LNweTHGVprEEFV0VyzcFX", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Travel", "uri"=>"spotify:genre:0JQ5IMCbQBLCs3BmgQsgL7"}]},
{:uid=>"1sbjTlSAwpfTXjyDTr3yYg", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Society", "uri"=>"spotify:genre:0JQ5DAqbMKFLFBJyefzcxG"}, {"__typename"=>"PodcastTopic", "title"=>"Culture", "uri"=>"spotify:genre:0JQ5DAqbMKFP9ywiCs8qKW"}, {"__typename"=>"PodcastTopic", "title"=>"Self-help", "uri"=>"spotify:genre:0JQ5DAqbMKFLPhtHltUeTr"}]},
{:uid=>"4oyjPyWss5TPqigIZWkli1", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Careers", "uri"=>"spotify:genre:0JQ5DAqbMKFMnJvsZliRJL"}, {"__typename"=>"PodcastTopic", "title"=>"Business", "uri"=>"spotify:genre:0JQ5DAqbMKFK0EBNV8Wn6R"}]},
{:uid=>"2G3nqDZOKZ0wWeXbBu5v5A", :genres=>[]},
{:uid=>"2HDYHI2RKjeJxL21636Opg", :genres=>[]},
{:uid=>"0SH5lhsW8vV6OgmrXRQXAD", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Technology", "uri"=>"spotify:genre:tech_interviews_podcasts"}]},
{:uid=>"25H3VGTKQUo1ImawOBVbvD", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Pop culture", "uri"=>"spotify:genre:0JQ5IMCbQBLm1xnyRGiyzw"}, {"__typename"=>"PodcastTopic", "title"=>"Personal stories", "uri"=>"spotify:genre:0JQ5DAqbMKFIHya0xgnxbE"}, {"__typename"=>"PodcastTopic", "title"=>"Entertainment", "uri"=>"spotify:genre:entertainment_v2_podcasts"}]},
{:uid=>"0dSpx5nyMFMYN5VuqMjuKB", :genres=>[]},
{:uid=>"1JjaISucgFCsDvwQ70F565", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"History", "uri"=>"spotify:genre:0JQ5DAqbMKFKK9EFSCDuOS"}]},
{:uid=>"33YGo4H4vtSzMTBq0DUwCS", :genres=>[]},
{:uid=>"4c9ZKaFtEKweSYOlYvxfvp", :genres=>[]},
{:uid=>"13KuPwWHzjWHgO00FBnW9a", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Relationships", "uri"=>"spotify:genre:0JQ5DAqbMKFIbOFW5Avg3a"}]},
{:uid=>"0TaF88QDTfKwY1IROFB4PM", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Health", "uri"=>"spotify:genre:health_podcasts"}]},
{:uid=>"3hOISuGT6b9kL0NO9Kkhpy", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Self-help", "uri"=>"spotify:genre:0JQ5DAqbMKFLPhtHltUeTr"}, {"__typename"=>"PodcastTopic", "title"=>"Comedy", "uri"=>"spotify:genre:0JQ5DAqbMKFNr6gDrHHVKL"}]},
{:uid=>"53Hp2QnRJgfELblzYE9pgj", :genres=>[]},
{:uid=>"55uEQazfxxZQTH2JOTg1KZ", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Relationships", "uri"=>"spotify:genre:0JQ5DAqbMKFIbOFW5Avg3a"}, {"__typename"=>"PodcastTopic", "title"=>"Sex", "uri"=>"spotify:genre:0JQ5IMCbQBLqakmO96jZ4G"}]},
{:uid=>"2QgeByrS2LzOl6PVZ2bskD", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Health", "uri"=>"spotify:genre:health_podcasts"}]},
{:uid=>"7EFqgGlk8aA9GHU9uvdwRR", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Comedy", "uri"=>"spotify:genre:0JQ5DAqbMKFNr6gDrHHVKL"}]},
{:uid=>"1A577x91QotwCsfN4JxF2q", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Personal stories", "uri"=>"spotify:genre:0JQ5DAqbMKFIHya0xgnxbE"}, {"__typename"=>"PodcastTopic", "title"=>"Comedy", "uri"=>"spotify:genre:0JQ5DAqbMKFNr6gDrHHVKL"}]},
{:uid=>"0gAIgnAeGO2FRnGVezehBk", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Health", "uri"=>"spotify:genre:health_podcasts"}, {"__typename"=>"PodcastTopic", "title"=>"Sex", "uri"=>"spotify:genre:0JQ5IMCbQBLqakmO96jZ4G"}]},
{:uid=>"0a1kAklbcImPFF9UHQp8iq", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Society", "uri"=>"spotify:genre:0JQ5DAqbMKFLFBJyefzcxG"}, {"__typename"=>"PodcastTopic", "title"=>"Culture", "uri"=>"spotify:genre:0JQ5DAqbMKFP9ywiCs8qKW"}]},
{:uid=>"4ZjbzpHvRblaMVIZ0RaBfm", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Society", "uri"=>"spotify:genre:0JQ5DAqbMKFLFBJyefzcxG"}, {"__typename"=>"PodcastTopic", "title"=>"Culture", "uri"=>"spotify:genre:0JQ5DAqbMKFP9ywiCs8qKW"}, {"__typename"=>"PodcastTopic", "title"=>"Business", "uri"=>"spotify:genre:0JQ5DAqbMKFK0EBNV8Wn6R"}]},
{:uid=>"38qloKR90VnAFJ2zNeCqLN", :genres=>[]},
{:uid=>"0LZHZHWjUddEvNaY3NM98q", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Language", "uri"=>"spotify:genre:0JQ5DAqbMKFGvEvBJcLHVZ"}]},
{:uid=>"2i2lwnhC1YnY3eB4po0EAA", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Documentary", "uri"=>"spotify:genre:0JQ5DAqbMKFCWOPjGCVIq4"}, {"__typename"=>"PodcastTopic", "title"=>"Culture", "uri"=>"spotify:genre:0JQ5DAqbMKFP9ywiCs8qKW"}, {"__typename"=>"PodcastTopic", "title"=>"Entertainment", "uri"=>"spotify:genre:entertainment_v2_podcasts"}]},
{:uid=>"2UQCZQyHUGzsPRHc2ZfxBZ", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Health", "uri"=>"spotify:genre:health_podcasts"}]},
{:uid=>"678FvchfNePfRqdHoxa0Eo", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"How-to", "uri"=>"spotify:genre:how_to_podcasts"}, {"__typename"=>"PodcastTopic", "title"=>"Technology", "uri"=>"spotify:genre:tech_interviews_podcasts"}]},
{:uid=>"6OMwqFKCAc2h26J8kPU0XA", :genres=>[]},
{:uid=>"0fL9gg6nmWXNGtToMYsWbT", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Careers", "uri"=>"spotify:genre:0JQ5DAqbMKFMnJvsZliRJL"}]},
{:uid=>"3TNsKUGlP9YbV1pgy3ACrW", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Technology", "uri"=>"spotify:genre:tech_interviews_podcasts"}]},
{:uid=>"2PUoQB330ft0sTzSNoCPrH", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Society", "uri"=>"spotify:genre:0JQ5DAqbMKFLFBJyefzcxG"}, {"__typename"=>"PodcastTopic", "title"=>"Culture", "uri"=>"spotify:genre:0JQ5DAqbMKFP9ywiCs8qKW"}]},
{:uid=>"2p0Vx75OmfsXktyLBuLuSf", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Careers", "uri"=>"spotify:genre:0JQ5DAqbMKFMnJvsZliRJL"}, {"__typename"=>"PodcastTopic", "title"=>"Technology", "uri"=>"spotify:genre:tech_interviews_podcasts"}]},
{:uid=>"7tE9shw3IlK99kgFeJ6I8J", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Technology", "uri"=>"spotify:genre:tech_interviews_podcasts"}]},
{:uid=>"2DQflwyaV6dkaAciHsZAY3", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Football", "uri"=>"spotify:genre:0JQ5DAqbMKFLPwE3vGBDOP"}]},
{:uid=>"4n4x6T7nMVM1CTruVPEO4p", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Careers", "uri"=>"spotify:genre:0JQ5DAqbMKFMnJvsZliRJL"}, {"__typename"=>"PodcastTopic", "title"=>"Business", "uri"=>"spotify:genre:0JQ5DAqbMKFK0EBNV8Wn6R"}, {"__typename"=>"PodcastTopic", "title"=>"Technology", "uri"=>"spotify:genre:tech_interviews_podcasts"}]},
{:uid=>"70Ty0iK2xwOGzcDJhMy1eK", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Business", "uri"=>"spotify:genre:0JQ5DAqbMKFK0EBNV8Wn6R"}]},
{:uid=>"1QZpU97vfwRBjMFWLHwExp", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Comedy", "uri"=>"spotify:genre:0JQ5DAqbMKFNr6gDrHHVKL"}]},
{:uid=>"0S1h5K7jm2YvOcM7y1ZMXY", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"How-to", "uri"=>"spotify:genre:how_to_podcasts"}, {"__typename"=>"PodcastTopic", "title"=>"Technology", "uri"=>"spotify:genre:tech_interviews_podcasts"}]},
{:uid=>"0xSfxhV2n0GSTtWP57H5VO", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Technology", "uri"=>"spotify:genre:tech_interviews_podcasts"}]},
{:uid=>"0lko8aKdFmeU7pgyAuOX25", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Careers", "uri"=>"spotify:genre:0JQ5DAqbMKFMnJvsZliRJL"}, {"__typename"=>"PodcastTopic", "title"=>"Technology", "uri"=>"spotify:genre:tech_interviews_podcasts"}]},
{:uid=>"2Ww2e4JNO2cfxWC2ImR7DJ", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Careers", "uri"=>"spotify:genre:0JQ5DAqbMKFMnJvsZliRJL"}, {"__typename"=>"PodcastTopic", "title"=>"Business", "uri"=>"spotify:genre:0JQ5DAqbMKFK0EBNV8Wn6R"}, {"__typename"=>"PodcastTopic", "title"=>"Technology", "uri"=>"spotify:genre:tech_interviews_podcasts"}]},
{:uid=>"62TXefpPe4FAJ3xIyihaET", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Relationships", "uri"=>"spotify:genre:0JQ5DAqbMKFIbOFW5Avg3a"}, {"__typename"=>"PodcastTopic", "title"=>"Technology", "uri"=>"spotify:genre:tech_interviews_podcasts"}]},
{:uid=>"0G3ZhYVoVIKWVbbATFsm6X", :genres=>[]},
{:uid=>"13Tz6g7tCIGvTv7YlCsIHb", :genres=>[]},
{:uid=>"3RhgmodnepEHEoBgFwpPVN", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Society", "uri"=>"spotify:genre:0JQ5DAqbMKFLFBJyefzcxG"}, {"__typename"=>"PodcastTopic", "title"=>"Culture", "uri"=>"spotify:genre:0JQ5DAqbMKFP9ywiCs8qKW"}]},
{:uid=>"6SXnsND0qzAcMAFpfy2JP1", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Technology", "uri"=>"spotify:genre:tech_interviews_podcasts"}]},
{:uid=>"1do6Oa0fxKFyw1Yt1IlBIk", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Economics", "uri"=>"spotify:genre:0JQ5IMCbQBLkCuGhI0Epb1"}, {"__typename"=>"PodcastTopic", "title"=>"Business", "uri"=>"spotify:genre:0JQ5DAqbMKFK0EBNV8Wn6R"}, {"__typename"=>"PodcastTopic", "title"=>"Technology", "uri"=>"spotify:genre:tech_interviews_podcasts"}]},
{:uid=>"5vaBQ06qUNNU5w90KMnqw8", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Society", "uri"=>"spotify:genre:0JQ5DAqbMKFLFBJyefzcxG"}, {"__typename"=>"PodcastTopic", "title"=>"Culture", "uri"=>"spotify:genre:0JQ5DAqbMKFP9ywiCs8qKW"}, {"__typename"=>"PodcastTopic", "title"=>"Business", "uri"=>"spotify:genre:0JQ5DAqbMKFK0EBNV8Wn6R"}]},
{:uid=>"6GSnbFz5qzNuKnLmGzQbPc", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Society", "uri"=>"spotify:genre:0JQ5DAqbMKFLFBJyefzcxG"}, {"__typename"=>"PodcastTopic", "title"=>"Science", "uri"=>"spotify:genre:0JQ5IMCbQBLzqj7yQzZb03"}, {"__typename"=>"PodcastTopic", "title"=>"Culture", "uri"=>"spotify:genre:0JQ5DAqbMKFP9ywiCs8qKW"}]},
{:uid=>"58dJK6bbqEqb86LGYU3ggz", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Marketing", "uri"=>"spotify:genre:0JQ5IMCbQBLjlqsYQ6tkLI"}, {"__typename"=>"PodcastTopic", "title"=>"Business", "uri"=>"spotify:genre:0JQ5DAqbMKFK0EBNV8Wn6R"}, {"__typename"=>"PodcastTopic", "title"=>"Technology", "uri"=>"spotify:genre:tech_interviews_podcasts"}]},
{:uid=>"3Hyh3BLScG1rvl7Fh7EYkW", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Business", "uri"=>"spotify:genre:0JQ5DAqbMKFK0EBNV8Wn6R"}]},
{:uid=>"4popXRlArqiIwZF6LNh5H3", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Design & Architecture", "uri"=>"spotify:genre:0JQ5DAqbMKFDx4Q5Zh2Fzg"}, {"__typename"=>"PodcastTopic", "title"=>"Educational podcasts", "uri"=>"spotify:genre:educational_podcasts"}]},
{:uid=>"1o2ZogNQQmPKCntcdKnXPT", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Football", "uri"=>"spotify:genre:0JQ5DAqbMKFLPwE3vGBDOP"}]},
{:uid=>"7nqJajzyZo3gdisGk7XhQx", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"TV", "uri"=>"spotify:genre:0JQ5IMCbQBLo64OouK01L3"}, {"__typename"=>"PodcastTopic", "title"=>"Entertainment", "uri"=>"spotify:genre:entertainment_v2_podcasts"}]},
{:uid=>"2tbkgRH7TSYT93QanfJ3Rz", :genres=>[]},
{:uid=>"7xdHieDPwtEonYZSHOKH2z", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Entertainment", "uri"=>"spotify:genre:entertainment_v2_podcasts"}]},
{:uid=>"7j9e807YyfTicJmhu2eI2Y", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Self-help", "uri"=>"spotify:genre:0JQ5DAqbMKFLPhtHltUeTr"}, {"__typename"=>"PodcastTopic", "title"=>"Business", "uri"=>"spotify:genre:0JQ5DAqbMKFK0EBNV8Wn6R"}]},
{:uid=>"3fQkNGzE1mBF1VrxVTY0oo", :genres=>[]},
{:uid=>"0BlKMc0Zy6OfWiZVcgA34j", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Pop culture", "uri"=>"spotify:genre:0JQ5IMCbQBLm1xnyRGiyzw"}, {"__typename"=>"PodcastTopic", "title"=>"TV", "uri"=>"spotify:genre:0JQ5IMCbQBLo64OouK01L3"}]},
{:uid=>"709eX5lJ5bCfRGvnlAYu79", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Pop culture", "uri"=>"spotify:genre:0JQ5IMCbQBLm1xnyRGiyzw"}, {"__typename"=>"PodcastTopic", "title"=>"TV", "uri"=>"spotify:genre:0JQ5IMCbQBLo64OouK01L3"}, {"__typename"=>"PodcastTopic", "title"=>"Entertainment", "uri"=>"spotify:genre:entertainment_v2_podcasts"}]},
{:uid=>"097CHWYaMBPqudZsxOu2Ln", :genres=>[]},
{:uid=>"6JKysHC1QneF8dQgEazK5w", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Business", "uri"=>"spotify:genre:0JQ5DAqbMKFK0EBNV8Wn6R"}]},
{:uid=>"5nrgZBGhvFEhDXjaYdjI7K", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Technology", "uri"=>"spotify:genre:tech_interviews_podcasts"}]},
{:uid=>"1LnPMFQyBHDpLNOE8VWVL1", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Music history", "uri"=>"spotify:genre:0JQ5IMCbQBLubyEn3NCJAz"}]},
{:uid=>"6LXxKn1KMjPHjMK5OqzMQH", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Business", "uri"=>"spotify:genre:0JQ5DAqbMKFK0EBNV8Wn6R"}]},
{:uid=>"6JwLR0ZYVTZmt3RGNCWHEH", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Comedy", "uri"=>"spotify:genre:0JQ5DAqbMKFNr6gDrHHVKL"}]},
{:uid=>"282ifFAdjiR1yBEKswEKnh", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Technology", "uri"=>"spotify:genre:tech_interviews_podcasts"}, {"__typename"=>"PodcastTopic", "title"=>"Food", "uri"=>"spotify:genre:0JQ5DAqbMKFNPUFuyD1Gs7"}]},
{:uid=>"3cjfq1REoqjCzSMksyv0d4", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Business", "uri"=>"spotify:genre:0JQ5DAqbMKFK0EBNV8Wn6R"}, {"__typename"=>"PodcastTopic", "title"=>"Technology", "uri"=>"spotify:genre:tech_interviews_podcasts"}]},
{:uid=>"31P6soC4zTPskQQklrVorW", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Society", "uri"=>"spotify:genre:0JQ5DAqbMKFLFBJyefzcxG"}, {"__typename"=>"PodcastTopic", "title"=>"Culture", "uri"=>"spotify:genre:0JQ5DAqbMKFP9ywiCs8qKW"}]},
{:uid=>"6dIJgWRjpFwGA5K9cDWjW2", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Business", "uri"=>"spotify:genre:0JQ5DAqbMKFK0EBNV8Wn6R"}]},
{:uid=>"7xzAHy5zOSFztWy0R0cmCx", :genres=>[]},
{:uid=>"7vD0FHksvrnjDVSktbdCVF", :genres=>[]},
{:uid=>"0qul7h6s77lJvbGH77LK3d", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Music history", "uri"=>"spotify:genre:0JQ5IMCbQBLubyEn3NCJAz"}]},
{:uid=>"7xN0obO7y5AR20v2KT7TBp", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Society", "uri"=>"spotify:genre:0JQ5DAqbMKFLFBJyefzcxG"}, {"__typename"=>"PodcastTopic", "title"=>"Science", "uri"=>"spotify:genre:0JQ5IMCbQBLzqj7yQzZb03"}, {"__typename"=>"PodcastTopic", "title"=>"Culture", "uri"=>"spotify:genre:0JQ5DAqbMKFP9ywiCs8qKW"}]},
{:uid=>"1jY2nqO17zUN5xEf31GiBb", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Science", "uri"=>"spotify:genre:0JQ5IMCbQBLzqj7yQzZb03"}, {"__typename"=>"PodcastTopic", "title"=>"Business", "uri"=>"spotify:genre:0JQ5DAqbMKFK0EBNV8Wn6R"}, {"__typename"=>"PodcastTopic", "title"=>"Technology", "uri"=>"spotify:genre:tech_interviews_podcasts"}]},
{:uid=>"13Majfu7ofTX0YCEzU2GF2", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Self-help", "uri"=>"spotify:genre:0JQ5DAqbMKFLPhtHltUeTr"}]},
{:uid=>"5h0duiPIzBUQXvcpmvShek", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Football", "uri"=>"spotify:genre:0JQ5DAqbMKFLPwE3vGBDOP"}]},
{:uid=>"6CXmyol5sWzs84WOWiBjbs", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Society", "uri"=>"spotify:genre:0JQ5DAqbMKFLFBJyefzcxG"}, {"__typename"=>"PodcastTopic", "title"=>"Documentary", "uri"=>"spotify:genre:0JQ5DAqbMKFCWOPjGCVIq4"}, {"__typename"=>"PodcastTopic", "title"=>"Culture", "uri"=>"spotify:genre:0JQ5DAqbMKFP9ywiCs8qKW"}]},
{:uid=>"21eTsGTyUjrZjpyPegZFwG", :genres=>[]},
{:uid=>"4yXsMW1CFOjL17OFbdca0L", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"History", "uri"=>"spotify:genre:0JQ5DAqbMKFKK9EFSCDuOS"}, {"__typename"=>"PodcastTopic", "title"=>"Stories", "uri"=>"spotify:genre:0JQ5DAqbMKFHv2c1dK1Jdi"}, {"__typename"=>"PodcastTopic", "title"=>"Educational podcasts", "uri"=>"spotify:genre:educational_podcasts"}]},
{:uid=>"7o0K5Jd2sAzcD2EsEdYjV4", :genres=>[]},
{:uid=>"49Hn6xOSuD8CAuiqfiwBeP", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Business", "uri"=>"spotify:genre:0JQ5DAqbMKFK0EBNV8Wn6R"}]},
{:uid=>"1KmDM2KUR7UdZ1wdJ17cSD", :genres=>[]},
{:uid=>"1PgVFKpBDrPkParYhJMcAR", :genres=>[]},
{:uid=>"3kLoIAHYzmtAMtOzPzGWtV", :genres=>[]},
{:uid=>"64DxVGa6wl3OUaoqceB4hn", :genres=>[]},
{:uid=>"4Q4kB5lhLSgDOZujlDCuIl", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Health", "uri"=>"spotify:genre:health_podcasts"}]},
{:uid=>"1M4l1D3R0KXBnN6w2wclyv", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Relationships", "uri"=>"spotify:genre:0JQ5DAqbMKFIbOFW5Avg3a"}]},
{:uid=>"31884KBvuQsrw4TDvWq6NX", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Beauty & Fashion", "uri"=>"spotify:genre:0JQ5IMCbQBLlXemwiylToM"}]},
{:uid=>"7tdmPrqC6gdExYaAQePxkY", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Finance", "uri"=>"spotify:genre:0JQ5IMCbQBLrxSDV6Xi6kN"}, {"__typename"=>"PodcastTopic", "title"=>"Business", "uri"=>"spotify:genre:0JQ5DAqbMKFK0EBNV8Wn6R"}]},
{:uid=>"7wkYuqWC8z51nfetiZCTbT", :genres=>[]},
{:uid=>"6bYXql5ROjSJxZjSZhgAgX", :genres=>[]},
{:uid=>"3U7lJPwhtyP3WyzcoYsRwU", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Finance", "uri"=>"spotify:genre:0JQ5IMCbQBLrxSDV6Xi6kN"}]},
{:uid=>"6GA15nwXtqXi1AIZu5mSN9", :genres=>[]},
{:uid=>"2mWQkByRfzyFKODZJsPMyq", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Film", "uri"=>"spotify:genre:0JQ5IMCbQBLBylyI0RX5u8"}, {"__typename"=>"PodcastTopic", "title"=>"Self-help", "uri"=>"spotify:genre:0JQ5DAqbMKFLPhtHltUeTr"}, {"__typename"=>"PodcastTopic", "title"=>"Comedy", "uri"=>"spotify:genre:0JQ5DAqbMKFNr6gDrHHVKL"}]},
{:uid=>"2kH3ec1ljTia7VmwYsm8Xt", :genres=>[]},
{:uid=>"4wE29GCPwbPvl0uTYn2tOd", :genres=>[]},
{:uid=>"3FDvbkn9G6ugYry0art4Kx", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Relationships", "uri"=>"spotify:genre:0JQ5DAqbMKFIbOFW5Avg3a"}]},
{:uid=>"3cNFVDuQLLNnsRoLmt7tNj", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Self-help", "uri"=>"spotify:genre:0JQ5DAqbMKFLPhtHltUeTr"}]},
{:uid=>"0MXNhbb3bR4qG05bpY4r9p", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Philosophy", "uri"=>"spotify:genre:0JQ5IMCbQBLjLJlIwYDak9"}, {"__typename"=>"PodcastTopic", "title"=>"Educational podcasts", "uri"=>"spotify:genre:educational_podcasts"}]},
{:uid=>"0OtHewggWkKDTWqYKl3txL", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Relationships", "uri"=>"spotify:genre:0JQ5DAqbMKFIbOFW5Avg3a"}]},
{:uid=>"1yl5ia4baVo50mXYcaObL2", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Society", "uri"=>"spotify:genre:0JQ5DAqbMKFLFBJyefzcxG"}, {"__typename"=>"PodcastTopic", "title"=>"Culture", "uri"=>"spotify:genre:0JQ5DAqbMKFP9ywiCs8qKW"}]},
{:uid=>"4Pn2T02GYIc1UV6G9clofz", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Marketing", "uri"=>"spotify:genre:0JQ5IMCbQBLjlqsYQ6tkLI"}]},
{:uid=>"15JW1Ua0B7FW6ze7F2rkbd", :genres=>[]},
{:uid=>"5iJbqIwN9AaQ6DzsQl9xCj", :genres=>[]},
{:uid=>"7LmEqTYA41Wf5ZkbfoqnWr", :genres=>[]},
{:uid=>"2rJjKdjeKHWYIYY6h4Aiul", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Parenting", "uri"=>"spotify:genre:0JQ5DAqbMKFC6MYl4K4nyR"}, {"__typename"=>"PodcastTopic", "title"=>"How-to", "uri"=>"spotify:genre:how_to_podcasts"}, {"__typename"=>"PodcastTopic", "title"=>"Self-help", "uri"=>"spotify:genre:0JQ5DAqbMKFLPhtHltUeTr"}]},
{:uid=>"6MtM47xr30FYGPVDSGKfag", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Health", "uri"=>"spotify:genre:health_podcasts"}, {"__typename"=>"PodcastTopic", "title"=>"Self-help", "uri"=>"spotify:genre:0JQ5DAqbMKFLPhtHltUeTr"}]},
{:uid=>"3v8pyFFppVuIL5SvNOa1om", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Careers", "uri"=>"spotify:genre:0JQ5DAqbMKFMnJvsZliRJL"}, {"__typename"=>"PodcastTopic", "title"=>"Finance", "uri"=>"spotify:genre:0JQ5IMCbQBLrxSDV6Xi6kN"}, {"__typename"=>"PodcastTopic", "title"=>"Travel", "uri"=>"spotify:genre:0JQ5IMCbQBLCs3BmgQsgL7"}]},
{:uid=>"3112QcElRKOeMLaMfD7nwR", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Self-help", "uri"=>"spotify:genre:0JQ5DAqbMKFLPhtHltUeTr"}]},
{:uid=>"2HGcJRYrjGnpce6bRp8UXm", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Self-help", "uri"=>"spotify:genre:0JQ5DAqbMKFLPhtHltUeTr"}]},
{:uid=>"5lEFhgPq9gcYU9MSXkALiZ", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Comedy", "uri"=>"spotify:genre:0JQ5DAqbMKFNr6gDrHHVKL"}]},
{:uid=>"5JQu91FRevsm4GSPr8JbYB", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Comedy", "uri"=>"spotify:genre:0JQ5DAqbMKFNr6gDrHHVKL"}]},
{:uid=>"4XrcIucy0RJQHFkONpxlBM", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Careers", "uri"=>"spotify:genre:0JQ5DAqbMKFMnJvsZliRJL"}, {"__typename"=>"PodcastTopic", "title"=>"Pop culture", "uri"=>"spotify:genre:0JQ5IMCbQBLm1xnyRGiyzw"}, {"__typename"=>"PodcastTopic", "title"=>"Beauty & Fashion", "uri"=>"spotify:genre:0JQ5IMCbQBLlXemwiylToM"}]},
{:uid=>"5cre2qahwFoYKpiwEHRgni", :genres=>[]},
{:uid=>"4OgszzJSGYfxqB1YejrihY", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Marketing", "uri"=>"spotify:genre:0JQ5IMCbQBLjlqsYQ6tkLI"}, {"__typename"=>"PodcastTopic", "title"=>"Relationships", "uri"=>"spotify:genre:0JQ5DAqbMKFIbOFW5Avg3a"}]},
{:uid=>"05aR1zxTnwQc6UOx1PaDuA", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Marketing", "uri"=>"spotify:genre:0JQ5IMCbQBLjlqsYQ6tkLI"}]},
{:uid=>"1mlDWCu2cUKSAsJEHg7HIP", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Marketing", "uri"=>"spotify:genre:0JQ5IMCbQBLjlqsYQ6tkLI"}, {"__typename"=>"PodcastTopic", "title"=>"Technology", "uri"=>"spotify:genre:tech_interviews_podcasts"}, {"__typename"=>"PodcastTopic", "title"=>"Design & Architecture", "uri"=>"spotify:genre:0JQ5DAqbMKFDx4Q5Zh2Fzg"}]},
{:uid=>"13qDj08lBR4ymzGhXIKy8t", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Careers", "uri"=>"spotify:genre:0JQ5DAqbMKFMnJvsZliRJL"}, {"__typename"=>"PodcastTopic", "title"=>"Marketing", "uri"=>"spotify:genre:0JQ5IMCbQBLjlqsYQ6tkLI"}]},
{:uid=>"1UjmXFsmYAe1ZwH1OFjcjh", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Culture", "uri"=>"spotify:genre:0JQ5DAqbMKFP9ywiCs8qKW"}, {"__typename"=>"PodcastTopic", "title"=>"Finance", "uri"=>"spotify:genre:0JQ5IMCbQBLrxSDV6Xi6kN"}]},
{:uid=>"7JEZXKdcU4YRJf36QyzfRC", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Careers", "uri"=>"spotify:genre:0JQ5DAqbMKFMnJvsZliRJL"}, {"__typename"=>"PodcastTopic", "title"=>"How-to", "uri"=>"spotify:genre:how_to_podcasts"}, {"__typename"=>"PodcastTopic", "title"=>"Personal stories", "uri"=>"spotify:genre:0JQ5DAqbMKFIHya0xgnxbE"}]},
{:uid=>"2xMmVkuQz8aCYvtib5pZsg", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Society", "uri"=>"spotify:genre:0JQ5DAqbMKFLFBJyefzcxG"}, {"__typename"=>"PodcastTopic", "title"=>"Culture", "uri"=>"spotify:genre:0JQ5DAqbMKFP9ywiCs8qKW"}, {"__typename"=>"PodcastTopic", "title"=>"Relationships", "uri"=>"spotify:genre:0JQ5DAqbMKFIbOFW5Avg3a"}]},
{:uid=>"6ekzL2wCS0h8blEFychtSH", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Relationships", "uri"=>"spotify:genre:0JQ5DAqbMKFIbOFW5Avg3a"}, {"__typename"=>"PodcastTopic", "title"=>"Sex", "uri"=>"spotify:genre:0JQ5IMCbQBLqakmO96jZ4G"}]},
{:uid=>"6DCIGjOUaenoKdY71N7NqI", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Science", "uri"=>"spotify:genre:0JQ5IMCbQBLzqj7yQzZb03"}, {"__typename"=>"PodcastTopic", "title"=>"Culture", "uri"=>"spotify:genre:0JQ5DAqbMKFP9ywiCs8qKW"}, {"__typename"=>"PodcastTopic", "title"=>"Sex", "uri"=>"spotify:genre:0JQ5IMCbQBLqakmO96jZ4G"}]},
{:uid=>"3Zwh39kXHAk9M6vZvofoxY", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Relationships", "uri"=>"spotify:genre:0JQ5DAqbMKFIbOFW5Avg3a"}, {"__typename"=>"PodcastTopic", "title"=>"Sex", "uri"=>"spotify:genre:0JQ5IMCbQBLqakmO96jZ4G"}, {"__typename"=>"PodcastTopic", "title"=>"Comedy", "uri"=>"spotify:genre:0JQ5DAqbMKFNr6gDrHHVKL"}]},
{:uid=>"0onjxuheqNMfUHem407NcQ", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Self-help", "uri"=>"spotify:genre:0JQ5DAqbMKFLPhtHltUeTr"}]},
{:uid=>"5gSocw3CVfhUpYEfslIxja", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"How-to", "uri"=>"spotify:genre:how_to_podcasts"}, {"__typename"=>"PodcastTopic", "title"=>"Technology", "uri"=>"spotify:genre:tech_interviews_podcasts"}]},
{:uid=>"6eRgjm2Wo07RSe0UHqb4dL", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"How-to", "uri"=>"spotify:genre:how_to_podcasts"}, {"__typename"=>"PodcastTopic", "title"=>"Business", "uri"=>"spotify:genre:0JQ5DAqbMKFK0EBNV8Wn6R"}]},
{:uid=>"2acKIpH0hrcGl0P8sU2Avj", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Self-help", "uri"=>"spotify:genre:0JQ5DAqbMKFLPhtHltUeTr"}]},
{:uid=>"0W7lo4UBMghDAdrTBCTXXW", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Business", "uri"=>"spotify:genre:0JQ5DAqbMKFK0EBNV8Wn6R"}]},
{:uid=>"1U1JkiGKNV53Ggl0uh31nL", :genres=>[]},
{:uid=>"2fUMDuTaHJrIhIeybVIfCz", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Educational podcasts", "uri"=>"spotify:genre:educational_podcasts"}]},
{:uid=>"0u8NBMvWajLvc66r9NsJJs", :genres=>[]},
{:uid=>"6QuhGAzGGOT63bRv2YJ7mo", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Relationships", "uri"=>"spotify:genre:0JQ5DAqbMKFIbOFW5Avg3a"}]},
{:uid=>"6xsBPNydno74vM2rvXoWrj", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Society", "uri"=>"spotify:genre:0JQ5DAqbMKFLFBJyefzcxG"}, {"__typename"=>"PodcastTopic", "title"=>"Culture", "uri"=>"spotify:genre:0JQ5DAqbMKFP9ywiCs8qKW"}]},
{:uid=>"0BNeFiVltF1YccNtpHapWu", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Language", "uri"=>"spotify:genre:0JQ5DAqbMKFGvEvBJcLHVZ"}]},
{:uid=>"1QjWQVEg4mtpOT1lXP216M", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Documentary", "uri"=>"spotify:genre:0JQ5DAqbMKFCWOPjGCVIq4"}, {"__typename"=>"PodcastTopic", "title"=>"History", "uri"=>"spotify:genre:0JQ5DAqbMKFKK9EFSCDuOS"}]},
{:uid=>"6FjTnEZCEWP44YQSEbQD6N", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Culture", "uri"=>"spotify:genre:0JQ5DAqbMKFP9ywiCs8qKW"}, {"__typename"=>"PodcastTopic", "title"=>"Entertainment", "uri"=>"spotify:genre:entertainment_v2_podcasts"}, {"__typename"=>"PodcastTopic", "title"=>"Comedy", "uri"=>"spotify:genre:0JQ5DAqbMKFNr6gDrHHVKL"}]},
{:uid=>"4MZcSXtqDGENW1RNUJntWD", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"Self-help", "uri"=>"spotify:genre:0JQ5DAqbMKFLPhtHltUeTr"}]},
{:uid=>"2QZNWpf0cAouTIj6UVsnTD", :genres=>[{"__typename"=>"PodcastTopic", "title"=>"How-to", "uri"=>"spotify:genre:how_to_podcasts"}]}]

# Creating categories

podcasts.each do |podcast|
  puts "Creating category #{podcast[:uid]}"
  if podcast[:genres]
    podcast[:genres].each do |genre|
      category = Category.find_or_create_by(name: genre["title"])
    end
  else
    "No genres for #{podcast[:uid]}"
  end
end

# Connecting podcasts to categories

podcasts.each do |podcast|
  puts "Creating genres #{podcast[:uid]}"
  if podcast[:genres]
    pp = Podcast.find_by(uid: podcast[:uid])
    if pp
      podcast[:genres].each do |genre|
        category = Category.find_by(name: genre["title"])
        if category
          pp.categories << category
        else
          puts "No category for #{genre["title"]}"
        end
      end
    end
  else
    "No genres for #{podcast[:uid]}"
  end
end
