name: Build Podiscover on Docker

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    name: Build Docker Image for Podiscover
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t podiscover:${{github.sha}} .
