name: Docker Artifact

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2'
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Run Rubocop
      run: bundle exec rubocop
    - name: Build and test Dockerfile
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: false
        tags: eaydev/podiscover:sha_${{ github.sha }}
    - name: List Docker images
      run: docker images
    - name: Save Docker image as file
      run: docker save eaydev/podiscover:sha_${{ github.sha }} | gzip > podiscover_sha_${{ github.sha }}.tar.gz
    - name: Upload Docker image as artifact
      uses: actions/upload-artifact@v2
      with:
        name: podiscover_sha_${{ github.sha }}
        path: podiscover_sha_${{ github.sha }}.tar.gz
