name: Build & Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2'
        
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    
    - name: Run Rubocop
      run: |
        bundle exec rubocop
    
  build:
    runs-on: ubuntu-latest
    needs: lint

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2'

    - name: Setup cache key and directory for gems cache
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-use-ruby-${{ hashFiles('**/Gemfile.lock') }}

    - name: Install dependencies
      run: |
        bundle config path vendor/bundle
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Build, Test & Publish Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: false
        tags: eaydev/podiscover:sha_${{ github.sha }}
        build-args: RUNNING_CI=true

    - name: List Docker Images
      run: docker images

  test:
    runs-on: ubuntu-latest
    needs: build

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          RAILS_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'

      - name: Setup cache key and directory for gems cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-use-ruby-${{ hashFiles('**/Gemfile.lock') }}

      - name: Install dependencies
        run: |
          bundle config path vendor/bundle
          gem install bundler
          bundle install --jobs 4 --retry 3
        
      - name: Create Database
        run: |
          cp config/database.yml.actions config/database.yml
          cat config/database.yml
          bundle exec rails db:prepare --trace
          bundle exec rails db:setup --trace
        env:
          RAILS_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_SECRET_ID: ${{ secrets.SPOTIFY_SECRET_ID }}
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}

      - name: Compile Assets
        run: |
          bundle exec rails assets:precompile --trace
        env:
          RAILS_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_SECRET_ID: ${{ secrets.SPOTIFY_SECRET_ID }}
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}

      - name: Run RSpec
        run: |
          COVERAGE=true bundle exec rspec --require rails_helper
        env:
          RAILS_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_SECRET_ID: ${{ secrets.SPOTIFY_SECRET_ID }}
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
